### ISSUE TITLE
Determinar "limite" de expansão de tiles

### ISSUE THREAD

**Issue by OttoRobba** [Expansion-Pack/Harvest-Sky#25]
Tal como o título diz - seria legal determinar até onde ir.

**Comment by Sestuna-bcl** [comment]
Levando em consideração o custo das tiles conforme o discutido no beta, acho que podemos limitar o jogo, por enquanto, a 200 tiles. isso é bastante no modelo atual de jogo, e da possibilidade de bastante expansão. Fazemos e teste assim e depois alinhamos com a experiencia do jogador.

**Comment by OttoRobba** [comment]
Por mim, parece bom! :)
