### ISSUE TITLE
Determinar custo dos tiles

### ISSUE THREAD

**Issue by OttoRobba** [Expansion-Pack/Harvest-Sky#27]
No momento eles custam 50 * (1 + número de tiles comprados).

Ou seja, 1o tile = 50, 2o = 100, 3o = 150....

Isso está bem caro no momento e, se vamos reduzir os tempos das plantas, fica ainda mais custoso. Precisamos definir novos valores.

**Comment by Sestuna-bcl** [comment]
acho que podemos montar uma outra mecânica. 
Talvez fazer o seguinte:
custo = 10 * (n/10) onde n é o numero de tiles compradas.
A ideia é que cada lote de 10 tiles custe 10 a mais que o lote anterior.
Primeiros 10 tiles custam 10 cada
os proximos 10 custam 20 e assim por diante.
O custo geral fica menor e o player pode se dar ao luxo de experimentar a posição de novos tiles sem isso custar demais pra ele.

**Comment by OttoRobba** [comment]
Interessante. Talvez dez tiles seja bastante (dá quase uma tela de largura) mas como vamos mexer nos custos das plantas, acho que pode funcionar legal.
Pro algoritmo ficar correto, seria:

    custo = 10 * Math.ceil(n/10)

Assim ele garante que 1/10, 2/10, etc... sejam 1. 11/10, 12/10, etc... sejam 2 e assim por diante.
Parece bem bom mano, vou fechar o issue o/
